### ISSUE TITLE
Unable to process sequence files with spaces in the name

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#121]
phylosift fails to process a file named Escherichia coli 101-1.fas, likely due to spaces in the name.

**Comment by gjospin** [comment]
This is starting a new convention that needs to be adopted for the whole project.

When writing system calls (using system() or `` or opening files with "gzip $filename |") quotes need to be added to every file name or paths.

Examples:
`"$Phylosift::Utilities::hmmalign --outformat afa --mapali " . $stockholm_file . " $hmm_file \"$new_candidate\" |"`
or
`\`mkdir -p "$self->{"fileDir"}"``
or
`$io_object = Bio::SeqIO->new( -file => "zcat \"$args{file}\" |", -format => $format );`

****\* Special case *****
Globs (< > and glob() ) need to have escaped characters added to the strings because it uses system calls and breaks down the variables.
Example : 
`$core_file_name = Phylosift::Utilities::escape_char(string=>$core_file_name);
my @array = glob("$core_file_name.*");`
