### ISSUE TITLE
create some basic perl module tests

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#177]
Perl module tests will be run by buildbot and during module installation, these can be used to test accuracy, regressions, support for various input types, etc.

**Comment by mayalowe** [comment]
I can whip up a couple simple module tests in addition to the standard perl ones we're already using.  I'm open to suggestions for first steps, but I can think of a few ways to start.
I would like to start using the other builders so that we can move towards using buildbot dynamically. So tests for different situations and tests of different scopes would be useful.

**Comment by koadman** [comment]
This looks like a duplicate of issue #46, so going to close this one.
