### ISSUE TITLE
Testing of PhymmBL

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#188]
Same sort of testing on simulated data as for Issue #185

This is the grand binner smackdown

**Comment by mayalowe** [comment]
Still attempting to install.  EisenNet being down over the weekend messed up the download/Install I was attempting on Friday, and PhymmBL's Makefile doesn't work properly and has required manual edits on my part.  Trying Install #4 right now, we'll see how it goes

**Comment by mayalowe** [comment]
Sent an email to Arthur Brady to try to figure out why the install isn't working.  PhymmBL's install script does not unpack any tarball it either downloads or comes packaged with, and even after manually unpacking the tarball the installation still does not complete because of "problems" it finds with the all.gbk.tar.gz file it downloads fresh from NCBI.  Tried installing on both Edhar (three times) and my Linux box (~8 times or so), each with no success.  Maybe next week will bring a response from Brady or an update...

**Comment by mayalowe** [comment]
Waiting for last data set to finish running, but essentially done
