### ISSUE TITLE
Discordance in the reporting of the number of reads placed in output files

### ISSUE THREAD

**Issue by hollybik** [gjospin/PhyloSift#210]
There is discordance between the number of placed reads that PhyloSift is reporting in the sequence_taxa.txt file and the taxasummary.txt files.

For example, in the output listed at /home/hollybik/phylosift_devel_20120511/PS_temp/pool5_AACACCT_test.fastq
Sequence_taxa is reporting 11310 unique reads placed via PhyloSift, but the taxasummary.txt file (summed value for column 4) is reporting 47414 reads placed.

**Comment by koadman** [comment]
It turns out there was a pretty significant error here, wherein the probability mass reported by pplacer was not being applied to read placements. Therefore each possible placement reported by pplacer for a particular read was being given equal probability. Sometimes the error introduced would be minimal, because the read had nearly equal probability on all reported branches, but usually the error would be considerable. This issue is fixed in commit 44dcda7 .  We need to check whether this issue also exists in master and if so either push a fix or merge devel to master immediately.
