### ISSUE TITLE
FastSearch can fail when sequence IDs are not unique

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#214]
When seq IDs are not unique, the writeCandidates code can fail to correctly match a sequence hit from lastal to the sequence it came from.

**Comment by gjospin** [comment]
It was decided that unless the -paired flag has been set (we can't keep track of more than 2 reads otherwise it gets messy and the memory usage grows too much), the two reads would get /1 and /2 added to the end of their IDs.  
Using interleaved fastq requires 2 paired reads for each molecule sequences.  Missing 1 of the two wouldn't allow for the ID name check to happen at the appropriate time and the sequence to ID matching later in FastSearch.pm would continue to fail.
