### ISSUE TITLE
Specify all module dependencies and their versions in README

### ISSUE THREAD

**Issue by audy** [gjospin/PhyloSift#239]
The readme states that PhyloSift requires BioPerl and Bio::Phylo but what versions? Also, not all dependencies are listed.

Is there something like Bundler for Perl?

**Comment by koadman** [comment]
I have added some notes to the readme about how to get any missing dependencies installed. Unfortunately an exhaustive list of dependencies that any particular system might be missing isn't really possible, since the direct dependencies of phylosift often have their own dependencies that may be missing. The recommend approach to install dependency software is `cpan`.
