### ISSUE TITLE
phylosift search -f does not clobber a pre-existing run when run_info.txt suggests a chunk is done

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#331]
-f , or --force should override any record stored in run_info.txt of what has already been processed.

**Comment by koadman** [comment]
note...this is not a problem when running `phylosift all -f` only with `phylosift search -f`.

**Comment by gjospin** [comment]
Do we want to simply clobber the blastDir ?

**Comment by gjospin** [comment]
Should be fixed with commit e59a4cd20aece86db03a3b7f55e29f927feb2d20

Might need to rethink the checks on completed chunks.  We are appending the run_info.txt. So we could get "chunk 1 completed" printed out multiple times if searches are run multiple times.
Also other single step modes (ie align or pplacer) don't write to run_info.txt.
