### ISSUE TITLE
--continue doesn't work 

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#333]
continue is supposed to allow a run started at e.g. the align stage to continue through placement and summary. It's currently broken. We should either fix it or remove it.

**Comment by koadman** [comment]
@gjospin Any thoughts on whether this should be fixed or removed? If fixed, how would it work with chunks? would the user be able to start with e.g. placement on a chunk and then have the run continue back around with search on the next chunk? Or would you only be able to finish a single chunk?

**Comment by gjospin** [comment]
The way I had it set up a while back (probably broken by now) was that we were still reading every chunk for the input data but only printing to the lastal streams whenever a chunk was not completed.
Ideally, we could use that mechanic to finish a chunk in progress then start the other chunks.
I would be in favor of being able to --continue a full run rather than a single chunk.
If we want to have the option to only continue a single chunk, maybe we should introduce --continue_chunk

**Comment by gjospin** [comment]
Fixed in commit d596c44f4440a8000d5ee5317e147be37d378f7b
