### ISSUE TITLE
Create a 1.0 beta release

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#343]
phylosift's functionality and operability is far enough along that we might be able to create a 1.0

**Comment by koadman** [comment]
I posted this to http://edhar.genomecenter.ucdavis.edu/~koadman/phylosift/releases/

Holly did some testing and found no obvious problems.

@hollybik can you close when web site updating and social media announcements are complete?

**Comment by hollybik** [comment]
I went through the website pretty extensively over the last few days to fix all the remaining documentation and make sure everything is now up to date and reflecting the command line structure in our v1.0.0 release. Also updated the workflow diagrams since some were outdated (commit b38b151f2395a4128386bb5929a35459ab0d6f00). 

Have now officially announced our v1.0.0 release on the web and twitter. Closing this issue, yeahhhh!!
