### ISSUE TITLE
Missing package version

### ISSUE THREAD

**Issue by gjospin** [gjospin/PhyloSift#406]
Need to package the version package with PS. Doesn't seem to be included in standard perl distributions.

**Comment by koadman** [comment]
In the past, the standalone packaging script DID include version.pm but it was removed because it was incompatible with many newer systems. Starting with perl 5.10, version.pm is built right into perl itself. So the correct way to handle this issue is not entirely clear.

**Comment by koadman** [comment]
A version.pm is being included in the "legacy" folder. This gets conditionally included when perl is < 5.1, as judged by `$[`. This bug re-emerged when the Command.pm interface was added because version.pm needed to be loaded at the earliest entry-point into phylosift, which shifted from Utilities.pm to Command.pm.
