### ISSUE TITLE
create .jnlp for rrna markers

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#421]
The 16S and 18S markers are very useful because they have much more comprehensive coverage of the microbial diversity than genome databases. Many users will want to view their samples on these reference trees.

**Comment by gjospin** [comment]
Are we also looking at add .html and .xml for those markers as well?

**Comment by koadman** [comment]
it would be nice to have the 16S, 18S, and concat all in the same xml -- then we don't need to touch the .jnlp. `guppy fat` can create a single xml with many .jplace embedded.

**Comment by koadman** [comment]
no need to think about .html here as far as i can tell.

**Comment by gjospin** [comment]
Actually, I think we do need to worry about it because add_jnlp requires a file handle that's related to the html file.
I think however that we don't need to add one file per marker, we can just add a link to the all the markers needed within the 1 html file for the whole sample.

I think I'm close to a resolution for this issue.

**Comment by koadman** [comment]
@gjospin implemented this one. done and dusted!
