### ISSUE TITLE
Download eukaryotic marker gene alignments Parfrey et al

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#55]
Package these into amphora markers.

**Comment by koadman** [comment]
also compare to dongying's marker set

**Comment by hollybik** [comment]
16 Individual gene alignments put into shared AMPHORA dropbox folder - Euk_MarkerGenes_Alignments_ParfreyEtal2010 

Since we had discussed doing things in a "taxonomy-free" approach, I assumed we'll just compare these Euk sequences to Donying's bacteria/archaea sequences directly without going by the annotations

Next step is to reformat alignments (if needed) and package into AMPHORA markers as stated above.

**Comment by gjospin** [comment]
Aligned sequences converted from Nexus format to Fasta don't have the same number of  columns (using readseq.jar downloaded from http://iubio.bio.indiana.edu/soft/molbio/readseq/java/.  Same behavior happens when using the GUI version from http://www.ebi.ac.uk/cgi-bin/readseq.cgi
Also the readseq program found some nameless sequences with 1 bp at the end of the alignments.
