### ISSUE TITLE
Identify viral genome databases, marker genes

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#56]

**Comment by hollybik** [comment]
Since viruses are such a diverse group, there is no common marker that we can use to cross all the domains.  Instead, there appear to be group-specific markers and things like signal peptides and transmembrane domains that we can capitalize upon.

Relevant tools we can leverage include the Viral Metagenome Annotation Pipeline (VMGAP): http://www.standardsingenomics.org/index.php/sigen/article/view/sigs.1694706

Marker genes across disparate virus groups (also lists PCR primers): http://works.bepress.com/cgi/viewcontent.cgi?article=1015&context=steven_wilhelm

New dimensions of the virus world discovered through metagenomics (inc. marker genes): http://www.sciencedirect.com/science/article/pii/S0966842X0900242X

Marker genes related to phages: http://statgen.ncsu.edu/~dahlia/journalclub/F03/jbact4529.pdf

**Comment by hollybik** [comment]
Adding in the links from our e-mail discussion this morning.

Phrever (viral/bacterial/eukaryotic protein families): http://pbil.univ-lyon1.fr/databases/phever/

ViralZone: http://viralzone.expasy.org/

**Comment by hollybik** [comment]
We've progressed with viruses after shopping around relevant databases and asking Dongying to run his protein family analyses on the existing EBI genome data. We may go back to some of these resources to pull out or compare marker genes, but for now I think we have a good idea of where to find virus data.
