### ISSUE TITLE
stream sequences through pipeline until placement stage

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#88]
A new version of rapsearch2 exists which supports streaming, so all programs up to the placement stage can stream input to output. This could enable very fast analysis of microbial community structure on the order of minutes instead of hours to initial results.

**Comment by koadman** [comment]
rapsearch2 with streaming has now been added. Guillaume determined that writing sequences to disk is still necessary during the search phase, but streaming is still possible.

**Comment by gjospin** [comment]
Using Last and Bowtie allows for full streaming. This has been implemented and pushed to Devel.

**Comment by gjospin** [comment]
It seems to be working so far on the devel branch.

We ended up breaking the input file(s) into chunks that are streamed all the way through to the placement step due to memory issues when reading the output from lastal.
In addition we are reading the marker lists only once and refering to a marker lookup table when needed for the extended markers to prevent having to loop over all the markers many times as well as disk IO issues.
